

<h2>How many comics can you count?</h2>


<button id="comic-button">Click Here</button>

<script>
     $('#comic-button').load(function (e){
          $.ajax({
              type: 'get',
              url: "template/comic.php",
              data: {data : true},
              dataType:"HTML",
              success: function(data)
              {
                  $('#comic').html(data) // The server's response is now placed inside your target div
              },
              error: function()
              {
                  alert("Failed to get data.");
            }
          }); // Ajax close
          return false;
</script>